/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_knziha_plod_plaindict_MainActivityUIBase */

#ifndef _Included_com_knziha_plod_plaindict_MainActivityUIBase
#define _Included_com_knziha_plod_plaindict_MainActivityUIBase
#ifdef __cplusplus
extern "C" {
#endif
#undef com_knziha_plod_plaindict_MainActivityUIBase_FLASH_DURATION_MS
#define com_knziha_plod_plaindict_MainActivityUIBase_FLASH_DURATION_MS 800L
#undef com_knziha_plod_plaindict_MainActivityUIBase_SHORT_DURATION_MS
#define com_knziha_plod_plaindict_MainActivityUIBase_SHORT_DURATION_MS 1500L
#undef com_knziha_plod_plaindict_MainActivityUIBase_LONG_DURATION_MS
#define com_knziha_plod_plaindict_MainActivityUIBase_LONG_DURATION_MS 2355L
#undef com_knziha_plod_plaindict_MainActivityUIBase_WINDOW_SIZE
#define com_knziha_plod_plaindict_MainActivityUIBase_WINDOW_SIZE 100L
/*
 * Class:     com_knziha_plod_plaindict_MainActivityUIBase
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_knziha_plod_plaindict_MainActivityUIBase_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_knziha_plod_plaindict_MainActivityUIBase
 * Method:    testPakVal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_knziha_plod_plaindict_MainActivityUIBase_testPakVal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_knziha_plod_plaindict_MainActivityUIBase
 * Method:    getPseudoCode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_knziha_plod_plaindict_MainActivityUIBase_getPseudoCode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
